name: Run Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # သင့်လိုအပ်သော Python version ထည့်ပါ

      - name: Install dependencies
        run: |
          pip install python-dotenv
          pip install python-telegram-bot  # Telegram library ထည့်ပါ

      - name: Run the bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # GitHub Secrets မှ Token
        run: |
          python loikaw_bot.py  # Bot script ကို run ပါ