name: Telegram Bot

on: [push]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Update to v4 for compatibility
    - name: Set up Python
      uses: actions/setup-python@v4  # Already using latest version
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python loikawbot.py
