name: Run LoikawBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # သင့်လိုအပ်သော Python version ထည့်ပါ

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv
          pip install python-telegram-bot --upgrade  # Telegram library

      - name: List project files (Optional Debugging)
        run: ls -R  # ဖိုင်များ စာရင်းကို စစ်ဆေးရန်

      - name: Run the bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # GitHub Secrets မှ Token
        run: |
          python loikaw_bot.py  # Bot script ကို run ပါ
          
